In [12]:
import pandas as pd

In [14]:
MLW_Meta = pd.read_csv('MLW_Meta.csv')

In [18]:
MLW = pd.read_csv('MLW - MLW.csv') #Problem with encoding of raw csv file. had to upload to google sheets and re-download

In [19]:
MLW

,CommunityName,BeachName,BeachCountrycode,BeachRegionalSea,BeachLength_m,BeachLocation,BeachType,EventDate,EventType,NatRef,...,G202,G203,G204,G205,G206,G207,G208,G210,G211,G213
0,HfjNUlYZ,wemeldinge,NL,North-east Atlantic Ocean,89,Urban,Sandy,20130807,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EMBLAS,Sarpi,TR,Black Sea,47,Urban,Pebbels,20190901,Cleanup,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Monitoraggio Strategia Marina – Ministero dell...,Sant'Anna Arresi Porto Pino,IT,Mediterranean Sea,99,NaN,NaN,20180323,Monitoring,NaN,...,NaN,1.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,NaN
3,Surfrider Foundation Europe,"17 Rue du 8 Mai 1945, 64110 Maz?res-Lezons, Fr...",Int,NaN,81,NaN,NaN,20150321,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN
4,Swiss Litter Report,Mammern swisslitterreport,DE,NaN,375,Rural,Pebbels,20171030,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3374,Swiss Litter Report,Bodensee_Steinach_Dolder_A,CH,NaN,92,Urban,Other (mixed),20170930,Cleanup,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3375,Monitoraggio Strategia Marina – Ministero dell...,Localit? Isola S. Andrea presso Marano e Grado,IT,Mediterranean Sea,99,NaN,NaN,20180322,Monitoring,NaN,...,1.0,2.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3376,Surfrider Foundation Europe,"60 Route de la Corniche, 29200 Brest, France",NaN,North-east Atlantic Ocean,750,NaN,NaN,20190629,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,0.0
3377,Surfrider Foundation Europe,"2 All?e de Barqueroute, 13620 Carry-le-Rouet, ...",FR,Mediterranean Sea,81,NaN,NaN,20150317,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN
3378,Marbona,"El Sombrerico, Almería",ES,Mediterranean Sea,100,Rural,Pebbels,20170103,Cleanup,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN

In [26]:
MLW.columns

Index(['CommunityName', 'BeachName', 'BeachCountrycode', 'BeachRegionalSea',
       'BeachLength_m', 'BeachLocation', 'BeachType', 'EventDate', 'EventType',
       'NatRef',
       ...
       'G202', 'G203', 'G204', 'G205', 'G206', 'G207', 'G208', 'G210', 'G211',
       'G213'],
      dtype='object', length=176)

In [29]:
MLW.iloc[:,14]

0       NaN
1       NaN
2       6.0
3       NaN
4       NaN
       ...
3374    NaN
3375    2.0
3376    NaN
3377    NaN
3378    NaN
Name: G1, Length: 3379, dtype: float64

In [31]:
MLW.iloc[:,175]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
3374    0.0
3375    NaN
3376    0.0
3377    NaN
3378    NaN
Name: G213, Length: 3379, dtype: float64

In [36]:
col = ['X','Y','FID','RecordSequenceID','UniqueID','SourceID','LocationFreqID','Location','Dataset','Organization','Other',
'CountryName_FromSource','SubCountry_L1_FromSource','SubCountry_L2_FromSource','Longitude1',
'Latitude1','Longitude2','Latitude2','TotalWidth_m',
'TotalLength_m','TotalArea_Sq_m','ShorelineName','WaterfrontName','BeachAreaLandcover','BeachType',
'EventType','TotalVolunteers','DateOriginal',
'DateStandardized','MonthYear','Year','MonthNum','Month',
'Day','StartTime',
'DOW','FieldObsevations',
'DebrisDescription','Totalltems_EventRecord','TotalClassifiedItems_EC2020',
'PCT_PlasticAndFoam','PCT_Glass_Rubber_Lumber_Metal','SUM_Hard_PlasticBeverageBottle','SUM_Hard_OtherPlasticBottle','SUM_HardOrSoft_PlasticBottleCap',
'SUM_other_PlasticOrFoamFoodContainer',
'SUM_Hard_BucketOrCrate','SUM_Hard_Lighter','SUM_OtherHardPlastic','SUM_PlasticOrFoamPlatesBowlsCup','SUM_HardSoft_PersonalCareProduc',
'SUM_Hard_LollipopStick_EarBu','SUM_Soft_Bag','SUM_Soft_WrapperOrLabel','SUM_Soft_Straw','SUM_Soft_OtherPlastic','SUM_Soft_CigaretteButts','SUM_Other_StringRingRibbon',
'SUM_Other__Net','SUM_Other_FishingLineLureRope','SUM_other_BuoysAndFloats','SUM_Foam_OtherPlasticDebris','SUM_Other_OtherPlasticDebris','NAME','COUNTRY','ISO_CODE',
'ISO_CC','ISO_SUB',
'ADMINTYPE','DISPUTED','NOTES','AUTONOMOUS',
'COUNTRYAFF','CONTINENT','LAND_TYPE','LAND_RANK','Shape__Area','Shape__Length','Count_',
'Soft_sheets','Other_StrapsTiesBands','Other_Glowsticks','OtherFishing']

In [37]:
df = pd.DataFrame(columns = col) #Creating our new dataframe in EC2020 schema

In [56]:
MLW.fillna(0, inplace = True) #replace NaN with 0 for analysis

In [57]:
df['X'] = MLW.iloc[:,10]

In [58]:
df['Y'] = MLW.iloc[:,11]

In [59]:
df

,X,Y,FID,RecordSequenceID,UniqueID,SourceID,LocationFreqID,Location,Dataset,Organization,...,CONTINENT,LAND_TYPE,LAND_RANK,Shape__Area,Shape__Length,Count_,Soft_sheets,Other_StrapsTiesBands,Other_Glowsticks,OtherFishing
0,4.000644,51.521333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41.547731,41.522233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8.622900,38.941110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.352569,43.283900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8.955317,47.655837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3374,9.436171,47.506299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3375,13.235470,45.713930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3376,-4.525456,48.366137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3377,5.160290,43.329100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3378,-1.849968,37.078449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
MLW.iloc[:,18] + MLW.iloc[:,19]

0        0.0
1        0.0
2       12.0
3       10.0
4        0.0
        ...
3374     5.0
3375     4.0
3376     6.0
3377     0.0
3378    12.0
Length: 3379, dtype: float64

In [64]:
MLW.iloc[:,19]

0       0.0
1       0.0
2       6.0
3       0.0
4       0.0
       ...
3374    1.0
3375    2.0
3376    4.0
3377    0.0
3378    0.0
Name: G8, Length: 3379, dtype: float64

In [65]:
MLW.iloc[:,18]

0        0.0
1        0.0
2        6.0
3       10.0
4        0.0
        ...
3374     4.0
3375     2.0
3376     2.0
3377     0.0
3378    12.0
Name: G7, Length: 3379, dtype: float64